### ISSUE TITLE
ImportError: '_imagingcms' from 'PIL'

### ISSUE THREAD

**Issue by synner88** [pikepdf/pikepdf#221]
I am testing some parsing options and when I try to parse a [test pdf](http://www.orimi.com/pdf-test.pdf), I get:
```
Traceback (most recent call last):
  File "pdf-img-extract.py", line 68, in <module>
    main()
  File "pdf-img-extract.py", line 63, in main
    raw_image.extract_to(fileprefix=dumpPath)
  File "/usr/local/lib/python3.8/site-packages/pikepdf/models/image.py", line 578, in extract_to
    extension = self._extract_to_stream(stream=bio)
  File "/usr/local/lib/python3.8/site-packages/pikepdf/models/image.py", line 526, in _extract_to_stream
    im = self._extract_transcoded()
  File "/usr/local/lib/python3.8/site-packages/pikepdf/models/image.py", line 464, in _extract_transcoded
    base_mode, palette = self.palette
  File "/usr/local/lib/python3.8/site-packages/pikepdf/models/image.py", line 254, in palette
    if self.icc:
  File "/usr/local/lib/python3.8/site-packages/pikepdf/models/image.py", line 394, in icc
    self._icc = ImageCms.ImageCmsProfile(iccbytesio)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageCms.py", line 172, in __init__
    self._set(core.profile_frombytes(profile.read()))
  File "/usr/local/lib/python3.8/site-packages/PIL/_util.py", line 19, in __getattr__
    raise self.ex
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageCms.py", line 23, in <module>
    from PIL import _imagingcms
ImportError: cannot import name '_imagingcms' from 'PIL' (/usr/local/lib/python3.8/site-packages/PIL/__init__.py)
```
Using:
- Windows 10
- Python 3.8.10 on Cygwin 3.2.0
- pikepdf 2.15.0 installed with pip 21.1.3

I understand it has something to do with PIL vs Pillow compatibility with Python 3.8?

**Comment by jbarlow83** [comment]
Do you have Pillow installed, and what is the version? Check `pip list`.
If the command `python -c 'from PIL import _imagingcms'` does not work, please close and report this to the Pillow project.

**Comment by synner88** [comment]
```
[syn@cygwin ~/Desktop]λ pip3.8 list installed | grep -iP '(pillow|pil)'
Pillow            8.3.1
[syn@cygwin ~/Desktop]λ python3.8 -c 'from PIL import _imagingcms'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name '_imagingcms' from 'PIL' (/usr/local/lib/python3.8/site-packages/PIL/__init__.py)
```
Thank you, @jbarlow83, you were right!
Closing issue as root cause seems to be in Pillow!

**Comment by synner88** [comment]
Found a similar issue reported in [Pillow Issue 5308](https://github.com/python-pillow/Pillow/issues/5308).
Solution is to install **liblcms2-dev** and reinstall Pillow.
Which resolved my problem!
Thank you for the support!
