### ISSUE TITLE
`open_outline()` fails with unreleased pikepdf 3.0.0b2.dev26+gdd58af8

### ISSUE THREAD

**Issue by mara004** [pikepdf/pikepdf#243]
Test case was reading the outline of the XMP Specification, Part 1. Looks like all files that use named destinations are affected. Possibly introduced with 8ecc79b?
```
Traceback (most recent call last):
  File "./t_gettoc.py", line 26, in <module>
    outline_pikepdf = get_pikepdf_toc(pdf)
  File "/home/mara/projects/pdfnodegraph/pdfnodegraph/processing/gettoc.py", line 104, in get_pikepdf_toc
    if len(outline.root) == 0:
  File "/home/mara/.local/lib/python3.8/site-packages/pikepdf/models/outlines.py", line 387, in root
    self._load()
  File "/home/mara/.local/lib/python3.8/site-packages/pikepdf/models/outlines.py", line 382, in _load
    self._load_level_outline(first_obj, root, 0, set())
  File "/home/mara/.local/lib/python3.8/site-packages/pikepdf/models/outlines.py", line 346, in _load_level_outline
    item = OutlineItem.from_dictionary_object(current_obj)
  File "/home/mara/.local/lib/python3.8/site-packages/pikepdf/models/outlines.py", line 188, in from_dictionary_object
    raise OutlineStructureError(
pikepdf.models.outlines.OutlineStructureError: Unexpected object type in Outline's /Dest: pikepdf.String("G1.456478")
```

**Comment by mara004** [comment]
I think the problematic line is [187](https://github.com/pikepdf/pikepdf/blob/8ecc79bf99ae9f1941b2462cca453ceab48b792a/src/pikepdf/models/outlines.py#L187):
```python3
if destination is not None and not isinstance(destination, Array):
```
String should also be allowed at this place.
