### ISSUE TITLE
Preloading the PDF files on Django sometimes corrupt the output.

### ISSUE THREAD

**Issue by Moath-Zaghdad** [pikepdf/pikepdf#285]
Hello,
I'm having a strange issue when I use a PDF file that is loaded once on Django start.

I'm trying to read PDF files as templates, they contain the XObjects, and replace their empty stream with something else that make use of their XObjects.
When I use that preloaded template, note `PDF_TEMPLATE`, it sometimes results in generating the pdf without some of the XObjects from the preloaded PDF file, note `test2_pdf`. However, when directly reading the PDF file from disc it always works, note `test1_pdf`.

### Sample code
Loading the templates on Django start **apps.py**
``` python
from django.apps import AppConfig


class TestAppNameConfig(AppConfig):

    def ready(self):
        from .views import load_pdf_template
        # load the template once on server start
        load_pdf_template()

```
**views.py**
``` python
import logging
import io
import pathlib

import django.http
import django.views.decorators.http

import pikepdf


PDF_TEMPLATE = dict()


def load_pdf_template():
    filename = pathlib.Path(__file__).parents[1] / 'pdf_templates' / 'test-pdf.pdf'
    PDF_TEMPLATE['test-pdf'] = pikepdf.Pdf.open(filename)

    filename = pathlib.Path(__file__).parents[1] / 'pdf_templates' / 'other-template.pdf'
    PDF_TEMPLATE['other-template'] = pikepdf.Pdf.open(filename)


def update_stream_content(template):
    pdf = pikepdf.Pdf.new()
    pdf.pages.extend(template.pages)

    pdf.pages[0].Contents = pdf.make_stream(b'\n'.join([
        b'q',
        b'0 0 1 rg',
        b'13 13 50 50 re f',
        b'1 0 1 rg',
        b'q 25 0 0 25 13 13 cm /C0 Do Q',
        b'Q'
    ]))

    in_mem = io.BytesIO()
    pdf.save(
        in_mem,
        preserve_pdfa=False,
        # compress_streams=False,
        stream_decode_level=pikepdf.StreamDecodeLevel.generalized,
        object_stream_mode=pikepdf.ObjectStreamMode.disable,
    )
    return in_mem.getvalue()

# this is the expected output, note that I commented everything after ID because the ID changes from PDF to another
FILE_CONTENT = b'%PDF-1.3\n%\xbf\xf7\xa2\xfe\n1 0 obj\n<< /Pages 2 0 R /Type /Catalog >>\nendobj\n2 0 obj\n<< /Count 1 /Kids [ 3 0 R ] /Type /Pages >>\nendobj\n3 0 obj\n<< /Contents 4 0 R /Group << /CS /DeviceRGB /I true /S /Transparency /Type /Group >> /MediaBox [ 0 0 75 75 ] /Parent 2 0 R /Resources 5 0 R /Type /Page /pdftk_PageNum 1 >>\nendobj\n4 0 obj\n<< /Length 58 /Filter /FlateDecode >>\nstream\nx\x9c+\xe42P0P0T(J\xe724V\x00"S\x03\x10*JUH\xe32\x84\xc9\x14*\x18\x99*\x80\xd4\x01)\x88\xaa\xe4\\\x05}g\x03\x05\x97|\x85@\xae@\x00\xdec\x0e\x16endstream\nendobj\n5 0 obj\n<< /ExtGState << /a0 << /CA 1 /ca 1 >> >> /XObject << /C0 6 0 R >> >>\nendobj\n6 0 obj\n<< /BBox [ 0 0 2 2 ] /FormType 1 /Matrix [ 1 0 0 1 0 0 ] /Subtype /Form /Type /Xobject /Length 80 /Filter /FlateDecode >>\nstream\nx\x9c3T0R\xc8\xe52\x04\x92\x86z\xa6\xa6FF\x16&\xe6&\x96\x16@.\x86\x80\xa1B2\x17\x884R0\xd0311774525@Se\x00\x947\x00\xaa\x03\x91(\xaa\x0c0\x05@\xe6A\xd4\xa3\x1a\x81\xac\nb_2W\x1a\x17\x00NB\x1f7endstream\nendobj\nxref\n0 7\n0000000000 65535 f \n0000000015 00000 n \n0000000064 00000 n \n0000000123 00000 n \n0000000310 00000 n \n0000000438 00000 n \n0000000523 00000 n \ntrailer << /Root 1 0 R /Size 7 /ID'
  # [<ee2b4a562162c9bc38f7e641f284867b><ee2b4a562162c9bc38f7e641f284867b>] >>\nstartxref\n757\n%%EOF\n


@django.views.decorators.http.require_http_methods(["GET"])
def test1_pdf(request):
    # this code works every time
    filename = pathlib.Path(__file__).parents[1] / 'pdf_templates' / 'test-pdf.pdf'
    template = pikepdf.Pdf.open(filename)
    file_content = update_stream_content(template)

    if file_content.find(FILE_CONTENT) == -1:
        return django.http.HttpResponse(file_content, content_type=generator.get_mime_type('pdf'), status=500)
    return django.http.HttpResponse(file_content, content_type=generator.get_mime_type('pdf'))


@django.views.decorators.http.require_http_methods(["GET"])
def test2_pdf(request):
    # this code sometimes does not work,  as a result, it returns a response with status code 500 
    file_content = update_stream_content(PDF_TEMPLATE['test-pdf'])

    if file_content.find(FILE_CONTENT) == -1:
        return django.http.HttpResponse(file_content, content_type=generator.get_mime_type('pdf'), status=500)
    return django.http.HttpResponse(file_content, content_type=generator.get_mime_type('pdf'))

``` 
### To reproduce
It might be hard to reproduce the issue, I used [`hey`](https://github.com/rakyll/hey) with 12 concurrent requests te reproduce it.
``` bash
$ hey -n 1000 -c 12 -m GET -t 10 http://localhost:8000/test2/
```

### Versions
pikepdf: 4.2.0
qpdf: 10.4.0
python: 3.9.9
django: 4.0

**Comment by jbarlow83** [comment]
If you save with `static_id=True`, the output IDs will be deterministic. This is not to PDF spec but helpful for testing in cases like this. 

Try putting a `threading.Lock` around `pdf.pages.extend(template.pages)`. I suspect there's some internal data structure at the C++ that gets linked between the two. 

Or perhaps the lock may need to be held till `.save`.

**Comment by Moath-Zaghdad** [comment]
I did what you suggested and it fixed the issue when I ran the Django project with the lightweight development web server, the  [runserver](https://docs.djangoproject.com/en/4.0/ref/django-admin/#runserver). However, when I ran it with [Gunicorn](https://gunicorn.org) an Exception happened:    
``` python
ERROR log Internal Server Error: /test2/
Traceback (most recent call last):
  File "/.../lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/.../lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/.../lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/.../lib/python3.9/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/.../views.py", line 172, in test_pdf2
    file_content = update_stream_content(PDF_TEMPLATE['test-pdf'])
  File "/.../views.py", line 124, in update_stream_content
    pdf.pages.append(template.pages[0])
pikepdf._qpdf.PdfError: /.../pdf_templates/test-pdf.pdf (): error getting raw stream data
```
This is the Gunicorn command with the configurations that I used:  
``` bash
$ gunicorn test_project.wsgi -b localhost:8551 --workers=8 --threads=2 --worker-class=gthread --preload
```
This exception is happening because I'm using **8** **workers** *AND* the **preload** flag, when I omitted the preload flag *OR* used only one worker the exception did not occur.
I wish I could use the preload flag, it saves memory and allows a faster project startup! Nevertheless, now that I know the problem I can tweak the Gunicorn configuration and not cause the exception.

Thank you very much @jbarlow83!

**Comment by jbarlow83** [comment]
In a complex process-thread-worker environment like I'd recommend against sharing pikepdf objects across worker boundaries. (To be precise you can share direct objects, but indirect objects are problematic because they are file-backed, lazy loaded and stateful.)

If gunicorn workers support a custom initializer function (like say,  `concurrent.futures.ProcessPoolExecutor`, the `initializer=` parameter), and function could load a thread local/process local copy. That way it won't have to be opened per request (assuming the overhead of that is worth reducing). (I don't know gunicorn much at all.)

**Comment by Moath-Zaghdad** [comment]
I removed the `preload` flag from the Gunicorn configs which made each worker load its own pikepdf objects. I can confirm that this is working.
I really appreciate your help, thanks @jbarlow83.
