### ISSUE TITLE
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)

### ISSUE THREAD

**Issue by BlackCatDevel0per** [pikepdf/pikepdf#341]
Hi, I'm creating library for django project for fast and simple processing pdf.
From tutorial i'm used:
```
import pikepdf
pdf = pikepdf.open('test_data/01.pdf')

output_pdf = 'test_data/encrypted.pdf'
passwd = 'test000000'
no_extracting = pikepdf.Permissions(extract=False)
#pdf.save(output_pdf, encryption=pikepdf.Encryption(user=passwd, owner=passwd, allow=no_extracting))
pdf.save(output_pdf, encryption=pikepdf.Encryption(user=passwd, owner=passwd, allow=no_extracting, R=4))
```
And it works fine, but if i use it in class:

My code:
```
# test.py
""" Crypt pdf Example """
import PDF4Cat

import resource
from time import time
from time import sleep

s_time = time()
PDF4Cat.Crypter('test_data/123.pdf').crypt_to(user_passwd="crypted", output_pdf='test_data/encrypted.pdf')
c_time = time()
print()
print(int(c_time - s_time), "s.")
print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss, "KB.")
```
Output:
```
Traceback (most recent call last):
  File "test.py", line 67, in <module>
    PDF4Cat.Crypter(filenames[0]).crypt_to(user_passwd="crypted", output_pdf='test_data/encrypted.pdf')
  File "/home/bcdev/PythonProjects/PDFScripts/PDF4Cat/crypt.py", line 32, in crypt_to
    allow=self.pdfPermissions(**perm)
  File "/home/bcdev/PythonProjects/PDFScripts/venv/lib/python3.7/site-packages/pikepdf/_methods.py", line 790, in save
    recompress_flate=recompress_flate,
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

Library code:
```
# PDFCat/__init__.py
from .crypt import Crypter
```

```
# PDF4Cat/cat.py
import os
import pikepdf


class PDF4Cat:
	from .helpers import run_in_subprocess
	def __init__(self, pdf_file=None, input_pdf_list: list=None, passwd: str='', progress_callback=None):
		if not pdf_file and input_pdf_list:
			pdf_file = input_pdf_list[0]
		elif pdf_file:
			pass
		else:
			raise TypeError("Required 1 argument of pdf_file, input_pdf_list. ")
		self.input_pdf_list = input_pdf_list
		self.pdf_file = pdf_file
		self.pdf_path = os.path.split(pdf_file)[0]
		self.pdf_name = os.path.basename(os.path.splitext(pdf_file)[0])
		self.pdf_filename = os.path.basename(pdf_file)

		self.pdf_new = pikepdf.Pdf.new
		self.pdf_open = pikepdf.Pdf.open

		self.pdfEncryption = pikepdf.Encryption
		self.pdfPermissions = pikepdf.Permissions

		self.passwd = passwd
		self.pdf = self.pdf_open(pdf_file, password=passwd)

		self.progress_callback = progress_callback
		self.counter = 0
		if not progress_callback:
			self.progress_callback = self.pc


	def pc(self, current, total) -> None:
		#
		print(f'Progress: {current} of {total} complete', end="\r")
		# if current != total:
		# 	print(f'Progress: {current} of {total} complete', end="\r")
		# else:
		# 	print(f'Progress: {current} of {total} complete')

	@property
	def pages_count(self) -> int:
		return len(self.pdf.pages)

	def save(self, output_pdf):
		self.pdf.save(output_pdf)
```

```
# PDF4Cat/crypt.py
import os

from .cat import PDF4Cat

class Crypter(PDF4Cat):
	def __init__(self, *args, **kwargs):
		super(Crypter, self).__init__(*args, **kwargs)

	# @PDF4Cat.run_in_subprocess
	def crypt_to(self, user_passwd: str = None, 
		owner_passwd: str = None, 
		perm: dict = None, 
		R: int = 4, 
		output_pdf: str = None) -> None:

		if not output_pdf:
			output_pdf = os.path.join(self.pdf_path, self.pdf_name+"_out.pdf")

		if not perm:
			perm = {'extract': False,}

		if not user_passwd:
			user_passwd = owner_passwd
		elif not user_passwd:
			owner_passwd = user_passwd
		elif not user_passwd and not owner_passwd:
			raise TypeError("Missing user or owner password!")


		self.pdf.save(output_pdf, encryption=self.pdfEncryption(
			user=user_passwd, owner=owner_passwd, R=R,
			allow=self.pdfPermissions(**perm)
			))

	def decrypt_to(self, output_pdf = None) -> None: # like save
		if not output_pdf:
			output_pdf = os.path.join(self.pdf_path, self.pdf_name+"_out.pdf")

		self.pdf.save(output_pdf)
```
All source: https://github.com/BlackCatDevel0per/PDF4Cat

I didn't find answers on Google, how can i fix it?
Python 3.7.3
```
# pip freeze (in venv)
lxml==4.8.0
packaging==21.3
pikepdf==5.1.2
Pillow==9.1.0
pyparsing==3.0.8
```

Thanks in advance.

**Comment by jbarlow83** [comment]
What version of pikepdf and operating system?

Can you reduce your code to a minimum reproducible example with a test file?

**Comment by BlackCatDevel0per** [comment]
> What version of pikepdf and operating system?
pikepdf 5.1.2
Debian 10
screenfetch:
```
         _,met$$$$$gg.           bcdev@bcdev
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 10 buster
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.19.0-20-amd64
   ,$$P'              `$$$.      Uptime: 5h 5m
  ',$$P       ,ggs.     `$$b:    Packages: 3236
  `d$$'     ,$P"'   .    $$$     Shell: zsh 5.7.1
   $$P      d$'     ,    $$P     Resolution: 1280x1024
   $$:      $$.   -    ,d$$'     DE: XFCE
   $$\;      Y$b._   _,d$P'      WM: Xfwm4
   Y$$.    `.`"Y$$$$P"'          WM Theme: Arc-Dark
   `$$b      "-.__               GTK Theme: Arc-Dark [GTK2]
    `Y$$                         Icon Theme: Papirus-Dark
     `Y$$.                       Font: Noto Sans 10.5
       `$$b.                     CPU: Intel Pentium Dual E2200 @ 2x 2.203GHz
         `Y$$b.                  GPU: GeForce GT 220/PCIe/SSE2
            `"Y$b._              RAM: 1065MiB / 3988MiB
                `""""           

```
> 
> Can you reduce your code to a minimum reproducible example with a test file?
```
import functools
import multiprocessing as mp
from queue import Empty

def run_in_subprocess(func):
	"""A decorator adding a kwarg to a function that makes it run in a subprocess.
	This can be useful when you have a function that may segfault.
	"""
	# This functools.wraps command makes this whole thing work
	# as a well-behaved decorator, maintaining the original function
	# name and docstring.
	@functools.wraps(func)
	def wrapper(*args, **kwargs):
		# Two extra kwargs, one public, are used for implementation.
		# One indicates that the user wants to run in a subprocess, the other
		# that the functtion is being called in the subprocess alreay.
		# The latter is the queue where the result gets posted to.
		run_in_subprocess = kwargs.pop('run_in_subprocess', True)
		subprocess_timeout = kwargs.pop('subprocess_timeout', None)
		queue = kwargs.pop('__queue', None)

		# create the machinery python uses to fork a subprocess
		# and run a function in it.
		if run_in_subprocess:
			q = mp.Queue()
			p = mp.Process(target=wrapper, args=args, kwargs={"run_in_subprocess":False, "__queue":q, **kwargs})
			# Because the use of this is avoiding crashes, rather than performance / parallelization
			# we wait for the subproces result immediately.
			p.start()
			try:
				result = q.get(timeout=subprocess_timeout)
				p.join()
			except Empty:
				p.terminate()
				raise TimeoutError("Function {} timed out with args: {}, {}".format(func, args, kwargs))
			# Pass on any exception raised in the subprocess
			if isinstance(result, BaseException):
				raise result
			return result
		else:
			# Run the function.  Eiher we are in the subprocess already or the user
			# does not want to run in the subproc.
			try:
				result = func(*args, **kwargs)
			except BaseException as error:
				# If running in standard mode just raise exceptions
				# as normal
				if queue is None:
					raise
				# Otherwise we pass the exception back to the caller
				# in place of the result
				result = error

			# This is optional, so the function can still just be called
			# normally with no effect.
			if queue is not None:
				queue.put(result)

			return result
	return wrapper


import os
import pikepdf


class PDF4Cat:
	run_in_subprocess = run_in_subprocess
	def __init__(self, 
		pdf_file=None, 
		input_pdf_list: list=None, 
		passwd: str='', 
		progress_callback=None):
		if not pdf_file and input_pdf_list:
			pdf_file = input_pdf_list[0]
		elif pdf_file:
			pass
		else:
			raise TypeError("Required 1 argument of pdf_file, input_pdf_list. ")
		self.input_pdf_list = input_pdf_list
		self.pdf_file = pdf_file
		self.pdf_path = os.path.split(pdf_file)[0]
		self.pdf_name = os.path.basename(os.path.splitext(pdf_file)[0])
		self.pdf_filename = os.path.basename(pdf_file)

		self.pdf_new = pikepdf.Pdf.new
		self.pdf_open = pikepdf.Pdf.open

		self.pdfEncryption = pikepdf.Encryption
		self.pdfPermissions = pikepdf.Permissions

		self.passwd = passwd
		self.pdf = self.pdf_open(pdf_file, password=passwd)

		self.progress_callback = progress_callback
		self.counter = 0
		if not progress_callback:
			self.progress_callback = self.pc

	# def save(self, output_pdf):
	# 	self.pdf.save(output_pdf)

	# def close(self, pdf):
	# 	pdf.close()

	def pc(self, current, total) -> None:
		#
		print(f'Progress: {current} of {total} complete', end="\r")
		# if current != total:
		# 	print(f'Progress: {current} of {total} complete', end="\r")
		# else:
		# 	print(f'Progress: {current} of {total} complete')

	@property
	def pages_count(self) -> int:
		return len(self.pdf.pages)

class Crypter(PDF4Cat):
	def __init__(self, *args, **kwargs):
		super(Crypter, self).__init__(*args, **kwargs)

	# @PDF4Cat.run_in_subprocess
	def crypt_to(self, user_passwd: str = None, 
		owner_passwd: str = None, 
		perm: dict = None, 
		R: int = 4, 
		output_pdf: str = None) -> None:

		if not output_pdf:
			output_pdf = os.path.join(self.pdf_path, self.pdf_name+"_out.pdf")

		if not perm:
			perm = {'extract': False,}

		if not user_passwd:
			user_passwd = owner_passwd
		elif not user_passwd:
			owner_passwd = user_passwd
		elif not user_passwd and not owner_passwd:
			raise TypeError("Missing user or owner password!")


		self.pdf.save(output_pdf, encryption=self.pdfEncryption(
			user=user_passwd, owner=owner_passwd, R=R,
			allow=self.pdfPermissions(**perm)
			))

	def decrypt_to(self, output_pdf = None) -> None: # like save
		if not output_pdf:
			output_pdf = os.path.join(self.pdf_path, self.pdf_name+"_out.pdf")

		self.pdf.save(output_pdf)

import resource
from time import time
from time import sleep

s_time = time()
Crypter('test_data/123.pdf').crypt_to(user_passwd="crypted", output_pdf='test_data/encrypted.pdf')
c_time = time()
print()
print(int(c_time - s_time), "s.")
print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss, "KB.")
```

**Comment by jbarlow83** [comment]
A [minimum reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) should contain no more code than is necessary to reproduce the issue. I'm asking to remove all concerns not necessary here (e.g. the profiling code, the unused run_in_subprocess function, the unused decrypt_to function)... in the process you may find the solution.

**Comment by jbarlow83** [comment]
Here's what a minimum reproducible example should look like:

```python
import pikepdf

pikepdf.Pdf.open('tests/resources/pal.pdf').save(
    '_.pdf',
    encryption=pikepdf.Encryption(
        owner=None,
    ),
)
```

I think you can tell what the issue was now. `None` is not allowable value for `owner`; an empty string must be used instead. Future versions will post a clearer error message for this.
