### ISSUE TITLE
ValueError: invalid arguments: (pikepdf._qpdf._ObjectList([Decimal('337.51312')]),)

### ISSUE THREAD

**Issue by hzxie** [pikepdf/pikepdf#458]
An error message occurred during the upload of [a certain PDF file](https://arxiv.org/pdf/2112.05504.pdf), stating ValueError: invalid arguments: (pikepdf._qpdf._ObjectList([Decimal('337.51312')]),).

```
[2023-03-15 16:26:57,834] [ERROR] [paperless.consumer] Error while consuming document 2112.05504.pdf: ValueError: invalid arguments: (pikepdf._qpdf._ObjectList([Decimal('337.51312')]),)
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 321, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 332, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 378, in run_pipeline
    pdfinfo = get_pdfinfo(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 165, in get_pdfinfo
    return PdfInfo(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 932, in __init__
    self._pages = _pdf_pageinfo_concurrent(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 709, in _pdf_pageinfo_concurrent
    executor(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 87, in __call__
    self._execute(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 666, in _pdf_pageinfo_sync
    page = PageInfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 746, in __init__
    self._gather_pageinfo(pdf, pageno, infile, check_pages, detailed_analysis)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 792, in _gather_pageinfo
    for info in _process_content_streams(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 594, in _process_content_streams
    yield from _find_form_xobject_images(pdf, container, contentsinfo)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 541, in _find_form_xobject_images
    yield from _process_content_streams(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 586, in _process_content_streams
    contentsinfo = _interpret_contents(container, initial_shorthand)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/pdfinfo/info.py", line 236, in _interpret_contents
    ctm = PdfMatrix(operands) @ ctm
  File "/usr/local/lib/python3.9/site-packages/pikepdf/models/matrix.py", line 56, in __init__
    raise ValueError('invalid arguments: ' + repr(args))
ValueError: invalid arguments: (pikepdf._qpdf._ObjectList([Decimal('337.51312')]),)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 385, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 379, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}") from e
documents.parsers.ParseError: ValueError: invalid arguments: (pikepdf._qpdf._ObjectList([Decimal('337.51312')]
```

See also the issue from the downstream application: https://github.com/paperless-ngx/paperless-ngx/issues/2894

**Comment by jbarlow83** [comment]
Malformed PDF; PdfMatrix has been removed and pikepdf.Matrix behaves correctly. No longer actionable for pikepdf.
