### ISSUE TITLE
[Feature Request] Add support for filling in PDF Form

### ISSUE THREAD

**Issue by allan-simon** [pikepdf/pikepdf#58]
If i'm not mistaken, it's supported by qpdf, having this feature will permit to at last throw away my subprocess call to pdftk :)

**Comment by allan-simon** [comment]
@jbarlow83 , sorry to up this feature request, I would be *really* interested by this feature (as that will permit me to throw a lot of code calling jython to call some java library , yes it's as ugly as you can imagine),  so if you think the feature is relevant but you don't have time to implement it , would you be interested by a PR ?

**Comment by jbarlow83** [comment]
Yes, a PR would be fantastic. I don't have the time to add this feature myself right now but I'd be happy to help out.

qpdf has a new API that should help for a lot of it. Read here:
http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.helper-classes

qpdf added these helper classes fairly recently. If I hadn't released pikepdf 1.0 the thing to do would be to break compatibility and automatically select an appropriate helper class to show to Python. That isn't possible right now, so you have to explicitly wrap a generic object to obtain the helper. Here's how it works for pikepdf.Page:
https://pikepdf.readthedocs.io/en/latest/api/models.html

I think the ideal thing to do would be to make the forms API look like wtforms or django forms, since that's familiar and would make it possible to translate HTML forms to PDF and vice versa.

**Comment by allan-simon** [comment]
I've started to look into this feature and just to improve my understanding why can't I directly edit the annotation field with existing form by doing like this:


```python
  def main():
      with pikepdf.open('output2.pdf') as pdf:
          for page in pdf.pages:
              if Name.Annots not in page:
                  continue
              annots = page.Annots
              for annot in annots:
                  if annot.Type != Name.Annot:
                      continue
                  if annot.Subtype == Name.Widget:
                      if Name.T in annot:                                                                                                                        
                          t = annot.T
                          if str(t) == "customer_name":
                              annot.V = "toto"                                                                   
  
          pdf.save("output.pdf")
```

as actually on  a form where I've edited manually the pdf using `evince`  to set myself `toto` in that field, I can see it in that very same variable `annot.V` ?

**Comment by mxfeinberg** [comment]
@allan-simon, did you end up finding a solution to your issue? I am also looking for a way to leverage QPDF/pikepdf to fill in form programmatically.

**Comment by allan-simon** [comment]
I've changed job in between, I'm asking former coworkers :)

**Comment by mxfeinberg** [comment]
Thanks! We're looking at wrapping QPDF with SWIG, but if there's an easier alternative, that would be nice.

**Comment by jbarlow83** [comment]
@mxfeinberg I do think it would be easier to extend pikepdf with a PR rather than wrap QPDF. pikepdf already wraps QPDF and solves a large number of practical issues in terms of how to represent QPDF's classes convert PDF data types to/from Python; you'd be doing that all over from scratch.

I also realize this is an in-demand feature and I can support a PR. Generally you'd just be writing simple pybind11 bindings for functions that already exist in QPDF, mainly:
* https://github.com/qpdf/qpdf/blob/master/include/qpdf/QPDFAcroFormDocumentHelper.hh
* https://github.com/qpdf/qpdf/blob/master/include/qpdf/QPDFAnnotationObjectHelper.hh
* https://github.com/qpdf/qpdf/blob/master/include/qpdf/QPDFFormFieldObjectHelper.hh

**Comment by Schirink** [comment]
For anybody interested in this feature, I've made two methods that seens to be working for now. I can't fully guarantee that they will work for all  Pdf's forms, but might be worth trying. If you have an idea to better optimize them, please let me know.

```python
from pikepdf import Pdf, Name, String, Array


def get_fields(pdf):
    """
    Extract info about the interactive fields present in the AcroForm of the
    pikepdf.PdfObject passed.
    Also, if the PDF has attr: NeedAppearances, ensures that it's value is True.
        param: pdf - instance of<pikepdf.PdfObject>
    returns: None, if the Pdf doesn't have an AcroForm, or a nested dict containing
    the fields names as the keys, with their value being a dict following this specification:
        '/FT' : field type;
        '/V' : current value present in the field;
        '/DV': if the field is one of the text types ('/Tx' or '/Ch'),
        this shows what value is the default one when the field
        has not yet been filled;
        'options': if the field is one of the button types ('/Btn' or '/RBtn'),
        this holds a list that contains the values used to represent when the
        button is `off` or `on`, or `off` and all the values used to represent
        the different options, in case it's a '/RBtn'. This method tries to
        ensure that options[0] will always be the `off` value, but this can't be
        guaranteed to always be true, since some Pdf-Form-Maker softwares might
        not follow all the Pdf 1.7 ISO specs.
    extra_info: some common types of fields:
        '/Tx': Text Field;
        '/Ch': Options List or Combo Box;
        '/Btn': Interactive Button;
        '/RBtn': Radio Button Parent;
        '/Sig': Signature Field (not suported yet, might be in the future)
    """
    if not hasattr(pdf.Root, "AcroForm"):
        return None
    if hasattr(pdf.Root.AcroForm, "NeedAppearances"):
        # If there's NeedAppearances in the Pdf AcroForm,
        # ensure that it's value is True
        pdf.Root.AcroForm.NeedAppearances = True

    fields = {}
    radio_repeats = []
    off_values = (
        "/Off",
        "/No",
        "/0",
        "/Null",
        "/False",
        "/Nill",
    )
    # These are some `off` values that I've seen in some Pdf Forms

    for i in range(len(pdf.pages)):
        for annot in pdf.pages[i].Annots:
            if not hasattr(annot, "FT"):  # This handles kids of radio buttons
                parent_str = str(annot.Parent.T)
                if parent_str in radio_repeats:
                    # check if annot.Parent isn't yet in the repeats list.
                    # if it is, just get the '/Yes' value
                    cur_list = fields[parent_str]["options"]
                    off_value = cur_list[0]
                    options = [item for item in annot.AP.N if item != off_value]
                    cur_list.extend(options)
                    fields[parent_str]["options"] = cur_list
                    continue
                options = [item for item in annot.AP.N]
                # access the kids keys of '/N' to get the
                # '/Off' and '/Yes' values of this first
                # radio button kid
                if options[0] not in off_values:
                    options.reverse()
                info_field = {
                    "/FT": "/RBtn",  # This '/RBtn' notation is not standartized
                    "/V": str(annot.AS),
                    "options": options,
                }
                fields.update({str(annot.Parent.T): info_field})
                radio_repeats.append(parent_str)
            else:
                if annot.FT == "/Btn":
                    if hasattr(annot, "A"):
                        # most likely JS Code utility button.
                        # They're not truly interactive, so skip
                        continue
                    # Else, must be a normal checkbox.
                    # It's way simpler to work with them
                    off_on_values = [item for item in annot.AP.N]
                    if off_on_values[0] not in off_values:
                        # Trying to ensure that index[0] will
                        # always be the '/Off' value
                        off_on_values.reverse()
                    info_field = {
                        "/FT": "/Btn",
                        "/V": str(annot.AS),
                        "options": off_on_values,
                    }
                elif annot.FT == '/Sig':
                    # Placeholder for signatures fields, since I need to
                    # do some research to see how their structure works
                    continue
                else:
                    # Otherwise, must be an text field
                    # ('/Tx' or '/Ch')
                    info_field = {
                        "/FT": str(annot.FT),
                        "/V": str(annot.V),
                        "/DV": str(annot.DV),
                    }
                fields.update({str(annot.T): info_field})
    return fields


def update_fields(pdf, fields):
    """
    Update Pdf interactive form fields values
        param: pdf - instance of<pikepdf.PdfObject> to update fields values
        param: fields - dict with fields names and their desired value
    For better performance, it's recommended to send only the fields names
    that need their values updated, as this method does nested iterations.
    The desired values sent are transformed into strings before being updated.
    You can send values that are not originally in fields of the type '/Ch'.
    They'll be added to these interactive fields, and their value switched to
    the desired value.
    warning: this method doesn't try to interpret booleans as `off`/`on` values
    of buttons. Instead, make the values of buttons fields be one of those listed in
    the 'options' list when using get_fields(). Otherwise, the field might not work as expected
    """
    for i in range(len(pdf.pages)):
        for annot in pdf.pages[i].Annots:
            for field, item in fields.items():
                value = str(item)
                if not hasattr(annot, "FT"):
                    if str(annot.Parent.T) != field:
                        continue
                    else:
                        foo = Name(value)
                        annot.Parent.AS = foo
                        annot.AS = foo
                        # The Parent holds in it's .AS the `on` value of the kid
                        # that's `on`, but the kid also needs tho have it's .AS
                        # set to the `on` value to show itself the right way
                        continue
                elif field != str(annot.T):
                    continue
                field_type = str(annot.FT)
                if field_type == "/Tx":
                    foo = String(value)
                    annot.V = foo
                    annot.DV = foo
                    # DV's are also updated because this "forces"
                    # most pdfviewers to display them
                elif field_type == "/Btn":
                    if hasattr(annot, "A"):
                        # This skips most JS Code buttons
                        continue
                    foo = String(value)
                    annot.AS = Name(value)
                    annot.V = foo
                    annot.DV = foo
                    # Normal checkboxes (usually) hold their values
                    # both in the AS and V
                elif field_type == "/Ch":
                    opt_list = [str(item) for item in annot.Opt]
                    if value not in opt_list:
                        # Add the value to the original '/Opt' -- why
                        # limit yourself to only the values that the pdf form
                        # creator wants you to use?
                        opt_list.append(value)
                        opt_list.sort()
                        annot.Opt = Array(opt_list)
                    foo = String(value)
                    annot.V = foo
                    annot.DV = foo
                elif field_type == "/Sig":
                    # Placeholder for signature fields. Needs more research
                    continue


if __name__ == '__main__':
    source1 = ""
    source2 = ""
    outpath = "OutputExample.pdf"
    new_pdf = Pdf.open(source1)
    fields = get_fields(new_pdf)
    print(fields)

    new_fields_source1 = {
        "Given Name Text Box": "Bababooie",
        "Family Name Text Box": "Bababooie",
        "Address 1 Text Box": "Bababooie",
        "House nr Text Box": 15,
        "Address 2 Text Box": "Bababooie",
        "Postcode Text Box": 56789,
        "City Text Box": "Bababooie",
        "Country Combo Box": "NoWhere",
        "Gender List Box": "Helicopter",
        "Height Formatted Field": "210",
        "Driving License Check Box": "/Yes",
        "Language 2 Check Box": "/Yes",
        "Language 4 Check Box": "/Yes",
    }
    new_fields_source2 = {"RadioCheck": "/Opt3", "OrdinaryRadio": "/Opt2"}

    update_fields(new_pdf, new_fields_source1)
    new_pdf.save(outpath)

```

These are the main samples that I'ved tested changing fields values, with good results:
source1:
[TestExample.pdf](https://github.com/pikepdf/pikepdf/files/6372636/TestExample.pdf)
source2: 
[RadioCheckBox_AcroForm.pdf](https://github.com/pikepdf/pikepdf/files/6372638/RadioCheckBox_AcroForm.pdf)

You can try these methods by changing the new_pdf source and new_fields to their corresponding file path, then running the script.

One problem that I've been trying to find a good solution to is: how to create an attribute `T` (the name of the field) for the radio buttons kids? Since they're unnamed, my idealization of these methods couldn't really be straightforward, so there's some spaguettio in handling this situation.

Another problem is: since the radio buttons kids are unnamed (which makes them kinda of an `IndirectObject`), I also needed to spaguettio my way towards updating their values. The problem is that, for now, I can only imagine two ways to ensure that the desired kid is `on` :
    -or iterate throught the `annot.Parent.Kids` reference, then iterate again throught the kid.N dict to compare if their value is the same of the one passed. If it is, then update it along with the `annot.Parent.AS` (really inneficient if there's a lot of radio buttons with a lot of kids, and `off` values being passed might make this not work as intended);
    -or set that all kids to have the `on` value of the desired kid, along with the `annot.Parent.AS` (this doesn't break the AcroForm nor the Pdf structure/stream, but it's not desirable)

As I was in a rush to make these, I opted with the later option.

Also, @jbarlow83, would you be OK with a future PR of both methods (without the radio buttons spaghettio, of course), maybe integrating them with the Pdf class itself or in a submodule "_utils.py_"? Or it's a must that these idealizations be pybinds of the QPDF helper classes? I particularly think that the QPDF implementation for updating fields it's a little restrictive, as they only update text fields. I was in a rush to make these methods, but, if possible, in the future I would like to submit both of these methods revised, improved and with some unit tests, but I'll need to do more research to guarantee some good testing capabilities.

**Comment by jbarlow83** [comment]
I'd prefer if it's in a submodule, especially if it doesn't use QPDF. I'd also prefer if we use QPDF in all cases currently supported by the QPDF implementation even if it has its limits. It makes the code much more maintainable in the long term and results in less duplication of effort to use QPDF whenever possible.

**Comment by robbat2** [comment]
@Schirink That code looks fantastic, ran into this PR when I needed to try and automate filling a specific form (sorry I can't share the form), however it doesn't seem to work, complaining about missing the `/AS`

```
Traceback (most recent call last):
  File "/home/robbat2/REDACTED/pikepdf-formtool.py", line 235, in <module>
    args.func(args)
  File "/home/robbat2/REDACTED/pikepdf-formtool.py", line 184, in formtool_get_fields
    fields = get_fields(new_pdf)
  File "/home/robbat2/REDACTED/./pikepdf-formtool.py", line 76, in get_fields
    "/V": str(annot.AS),
AttributeError: /AS
```

Your two functions are unmodified, this happens in the radio button path:
```
info_field = { 
  "/FT": "/RBtn",  # This '/RBtn' notation is not standartized
  "/V": str(annot.AS),
  "options": options,
  }
```

**Comment by Schirink** [comment]
@robbat2 Strange... From what I can see, It's one or more fields that don't have both the `/FT` and `/AS` keys. That's strange because Radio Buttons childs should hold their values in the `/AS` key (example 8.17, page 689 of the PDF 1.7 Reference -[https://archive.org/details/pdf1.7](url)). I think this might be a non-conformant field, or maybe it's not even a Radio Button child at all.

I undestand you aren't able do disclosure the pdf file itself, @robbat2, but could you give me some info about it? Knowing more about the file and the field itself allows me to help, and it might help improving these methods.

- What's the version of the file?
- Do you know what application was used to make this pdf form?
- Is there a signature field in this pdf? Or it's already signed with a digital certificate?

Also, if you wouldn't mind doing some quick-and-dirty debbuging to help, could you make a copy of the pdf, erase all the filled fields in the copy (so no private info will be shared), save it, run this copy through the snippet bellow and show to me the `Fields_Info.txt` content? This should write all the keys of all the fields in the file.

```python
from pikepdf import Pdf

input_file = r'' # path of your pdf form copy, remember to clean all fields before running

new_pdf = Pdf.open(input)

with open("Fields_Info.txt", "w") as f:
    for i in range(len(new_pdf.pages)):
        for annot in new_pdf.pages[i].Annots:
            for k in annot:
                f.write(f"{k} ")
            f.write("\n-------------\n") # spacing, just to separate fields
```

If you have Jupyter, it's better to run the snipet bellow and show that output instead, since it gives more info than the snippet above.

```python
from pikepdf import Pdf

input_file = r'' # path of your pdf form copy, remember to clean all fields before running

new_pdf = Pdf.open(input_file)

new_pdf.pages[0].Annots # this shows just the first page. If the pdf form has multiple pages, output each one in a new cell
```

Just to be clear, my intention with these snippets is just to see the structure of the fields.

I'm waiting for more info, thanks in advance

**Comment by dmjohnsson23** [comment]
I've created a [wrapper around PikePDF](https://github.com/dmjohnsson23/pdform) that is primarily aimed at supporting this functionality. It's not bullet-proof, and I imagine probably not exactly what the authors of PikePDF would be looking for to be upstreamed directly. However, it does support several use cases that neither PikePDF, nor the underlying QPDF, do; such as checkboxes with values other than "/Yes" and multiline text fields with word wrap, without relying on GenerateAppearances. I'm not comfortable enough with C/C++ to try and upstream any of this into PikePDF or QPDF myself, but perhaps what I've written will be useful as a jumping-off point for someone who does know C/C++. It does work, at least for my own use cases, and I feel like I've done a reasonably decent job at including comments referencing the spec and explaining what I'm doing. While I'm not sure I can directly contribute code upstream, I'm happy to do what I can.

**Comment by dmjohnsson23** [comment]
@jbarlow83 I have a lull period at work right now, and as we do rely on this, and would be greatly helped by having native form-filling capability, I'd actually be curious to see if by chance I can make this happen, if you could provide some pointers on where to start. 

You previously linked the QPDF classes that we could wrap of course, but if I were to try to do this I'd need more detailed guidance. To be clear, while I consider myself quite good with Python, my C++ experience is limited to a single course I took back in college a few years ago, and I know absolutely nothing about creating Python bindings for C++, so I'd be a total novice (I cloned the PikePDF repo and couldn't even figure out how to successfully build the thing on Linux). However, I'd genuinely be interested in learning if you know some good applicable tutorials or other resources I could read through.

My hope is that, since it would only be a matter of making a more or less 1-to-1 map of a C++ class to a Python class, it ought to be reasonably beginner-friendly endeavor, right? Then any higher-level logic could just be implemented in pure Python. (Or maybe those are famous last words...)

**Comment by jbarlow83** [comment]
Sure, I can give a few pointers to get started.

Here is the procedure to build on Linux. (Although it's best to create a fresh virtual environment to install 
 https://pikepdf.readthedocs.io/en/latest/installation.html#building-against-a-qpdf-source-tree
or if I do a push soon it will be here
 https://pikepdf.readthedocs.io/en/latest/source_build.html

We use a fairly recent version of qpdf, so your best bet is to build a recent qpdf as well.

When you have build, have a look at
https://github.com/pikepdf/pikepdf/blob/main/src/core/annotation.cpp

This is quite a straightforward wrapper that defines how the Python class named "Annotation" will be bound to the C++ class QPDFAnnotationObjectHelper. 

You'll need to make a similar one for QPDFAcroFormDocumentHelper, 
https://github.com/qpdf/qpdf/blob/main/include/qpdf/QPDFAcroFormDocumentHelper.hh

We use pybind11 as the binding layer. It has a pretty good tutorial document. For the most part you end saying, when this Python function is called, execute this C++ code. The binding layer takes care of converting Python types to C++ and vice versa; for primitive types this is automated by pybind11, and for pikepdf.Object/QPDFObjectHandle this is implemented in pikepdf.

The header will look this (and why)
```c++
    py::class_<QPDFAcroFormDocumentHelper,   // bind to this C++ class
        std::shared_ptr<QPDFAcroFormDocumentHelper>,  // pybind11 should store this object in a shared_ptr
        QPDFDocumentHelper>   // this C++ class is a subclass of QPDFDocumentHelper, and this directive tells the binding layer about that because it needs to know
(m, "AcroForm") // attach to python module named m with name "AcroForm"
        .def(py::init<QPDF &>(), py::keep_alive<0, 1>())   // this class will be allocated from a pikepdf.Pdf
```


The documentation and type hints go in _core.pyi

**Comment by dmjohnsson23** [comment]
Thanks! I think I finally managed to get a working build. Now for the real fun.

**Comment by jbarlow83** [comment]
pikepdf has supported interactive AcroForm forms for some time now — see the [Interactive Forms](https://pikepdf.readthedocs.io/en/latest/topics/interactive_forms.html) docs — so you can read and *fill* fields without shelling out to pdftk:

```python
pdf = Pdf.open('form.pdf')
form = pdf.acroform
for name, field in form.items():
    if field.is_text:
        field.set_value('new value')   # updates /V and regenerates the appearance
pdf.save('filled.pdf')
```

`AcroFormField.set_value(value, need_appearance=True)` sets the value and regenerates the field appearance stream. The upcoming v10.9 adds `AcroForm.validate()` / `transform_annotations()` for forms edited structurally.

Closing as resolved by the existing AcroForm interface — please open a new issue if a particular field type isn't handled.
