### ISSUE TITLE
pikepdf 9.1.2 won't build with setuptools 72.2.0

### ISSUE THREAD

**Issue by Schamschula** [pikepdf/pikepdf#604]
It seems that `pyproject.toml` is overly restrictive by specifying

`requires = ["setuptools >= 61, <= 72", "wheel >= 0.37", "pybind11 >= 2.10.1"]`

that means that the build with `setuptools` 72.2.0 fails.

In order to update the MacPorts Portfile I had to patch this out.

See: https://github.com/macports/macports-ports/commit/772a94fd5847824a3e7ab7c52af13484c25967f1

**Comment by jbarlow83** [comment]
The restriction is in place because setuptools 72.x fails with pypy on all platforms, deep in the part of setuptools that manages the C++ compiler. I don't know why. I'm hoping other people will figure it out without me having to investigate. Even if it's fixed, there are several versions of setuptools that need to be blacklisted.

**Comment by Schamschula** [comment]
So my build machine and MacPorts CI are hallucinating?

All platforms (all the way back to macOS 10.6 32 bit) and all supported versions of python (3.8 to 3.12) built pikepdf cleanly with setuptools 72.2.0.

I have no plans to abandon MacPorts for Python virtual environments in order to install endless parallel package versions. Backward compatibility, or the lack thereof,  seems to the Achilles heel of Python. Case in point numpy 2.0.x.

**Comment by jbarlow83** [comment]
Here is the issue, reproducible on setuptools >= 72 including 73, affecting PyPy 3.9 on macOS and Linux. CPython is not affected.

https://github.com/pikepdf/pikepdf/actions/runs/10497992273/job/29082003764

```
 Traceback (most recent call last):
    File "/opt/python/pp39-pypy39_pp73/lib/pypy3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
      main()
    File "/opt/python/pp39-pypy39_pp73/lib/pypy3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
    File "/opt/python/pp39-pypy39_pp73/lib/pypy3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 271, in build_wheel
      return _build_backend().build_wheel(
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 415, in build_wheel
      return self._build_with_temp_dir(
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 110, in <module>
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/__init__.py", line 108, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
      return run_commands(dist)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
      dist.run_commands()
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
      self.run_command(cmd)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/dist.py", line 945, in run_command
      super().run_command(command)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
      cmd_obj.run()
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
      self.run_command("build")
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/dist.py", line 945, in run_command
      super().run_command(command)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
      cmd_obj.run()
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
      self.distribution.run_command(command)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/dist.py", line 945, in run_command
      super().run_command(command)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
      cmd_obj.run()
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/command/build_ext.py", line 93, in run
      _build_ext.run(self)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
      self.build_extensions()
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/pybind11/setup_helpers.py", line 287, in build_extensions
      super().build_extensions()
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
      self._build_extensions_serial()
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
      _build_ext.build_extension(self, ext)
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 581, in build_extension
      self.compiler.link_shared_object(
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/ccompiler.py", line 757, in link_shared_object
      self.link(
    File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 268, in link
      linker = (
  TypeError: 'NoneType' object is not subscriptable (key slice(None, None, None))
  
  ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Comment by Schamschula** [comment]
Sure, those failing CI builds both have `setuptools >= 61, != 72.1.0, != 72.2.0`.

Compare https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/216911 which was built using `setuptools  72.2.0`

**Comment by jbarlow83** [comment]
Our builders are doing different things. You're not building PyPy, which is where the build error occurs. That's CPython 3.9.

The constraint I was testing will select 73.0.1, the latest version, which also fails; so far everything above 72 fails for PyPy. I can narrow the constraint to PyPy only which will satisfy everyone until someone gets annoyed about it.
