### ISSUE TITLE
install failure on armhf

### ISSUE THREAD

**Issue by fmax** [pikepdf/pikepdf#7]
on a raspberry armv7 cpu 
Linux version 4.4.43-v7+ (gcc version 4.9.2 (Raspbian 4.9.2-10) )
```
pip install pikepdf
Collecting pikepdf
  Using cached https://files.pythonhosted.org/packages/30/bd/7afb368ea0872e64208e9940c729afde2c27eff7ffe1bbb28a64b1bb5340/pikepdf-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-burtbex3/pikepdf/setup.py", line 113, in <module>
        readme = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2736: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-burtbex3/pikepdf/
```

**Comment by jbarlow83** [comment]
You probably need to set `LANG=C.UTF-8` or use Python 3.7.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.
