### ISSUE TITLE
metadata: TypeError: sequence item 0: expected str instance, NoneType found

### ISSUE THREAD

**Issue by jeromerobert** [pikepdf/pikepdf#84]
When opening [this](https://github.com/jeromerobert/pdfarranger/files/4301666/683053.pdf) with pikepdf 1.9.0 to 1.10.2 on both linux and windows, with the following program:

```python
import pikepdf
with pikepdf.open("683053.pdf") as doc:
    with doc.open_metadata() as meta:
        pass
```
I get:

```
Traceback (most recent call last):
  File "/home/jerome/pdfshuffle/pdfshuffler/test.py", line 6, in <module>
    pass
  File "/usr/lib/python3/dist-packages/pikepdf/models/metadata.py", line 389, in __exit__
    self._apply_changes()
  File "/usr/lib/python3/dist-packages/pikepdf/models/metadata.py", line 454, in _apply_changes
    self._update_docinfo()
  File "/usr/lib/python3/dist-packages/pikepdf/models/metadata.py", line 410, in _update_docinfo
    value = converter.docinfo_from_xmp(value)
  File "/usr/lib/python3/dist-packages/pikepdf/models/metadata.py", line 172, in docinfo_from_xmp
    return '; '.join(xmp_val)
TypeError: sequence item 0: expected str instance, NoneType found

**Comment by jbarlow83** [comment]
Fixed as of v1.16.1, in commit fe8078.
