### ISSUE TITLE
docinfo is NOT consistent with XMP

### ISSUE THREAD

**Issue by def-fun** [pikepdf/pikepdf#90]
I want to delete all docinfo and add new, so that no other strange docinfo can be found from new pdf. 
[Docs](https://pikepdf.readthedocs.io/en/latest/api/main.html) told me that PDF DocumentInfo block is consistent with XMP by default. But, docinfo still there after I delete ALL Metadata.

My code in ubuntu 16 terminal:
```python
$ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pikepdf
>>> pdf=pikepdf.open('Contract-Manufacturing-Arrangements-for-Drugs--Quality-Agreements.pdf')
>>> pdf.docinfo
pikepdf.Dictionary({
  "/AssignedTo": "",
  "/Author": "FDA/CDER",
  "/Company": "FDA Dallas District Office",
  "/ContentTypeId": "0x0101006F3CD5214AFA3B4EB052EF62504A8D5C",
  "/CreationDate": "D:20161118145535-05'00'",
  "/Creator": "Acrobat PDFMaker 10.1 for Word",
  "/Dosage": "",
  "/GUIDANCE SECTION": "",
  "/Initial Triage": "",
  "/Keywords": "Contract Manufacturing Arrangements for Drugs: Quality Agreements Guidance for Industry",
  "/Manager": "O. D. Evans",
  "/ModDate": "D:20161122151017-05'00'",
  "/NCI Category": "",
  "/OS Response": "",
  "/Org Type": "",
  "/Organization": "",
  "/PROD TYPE": "",
  "/Producer": "Adobe PDF Library 10.0",
  "/Quality Metric": "",
  "/Resp": ", ",
  "/SourceModified": "D:20161118195431",
  "/Subject": "Guidance for Industry",
  "/Title": "Contract Manufacturing Arrangements for Drugs: Quality Agreements Guidance for Industry",
  "/_NewReviewCycle": "",
  "/_dlc_DocId": "WMY7AAHNVM6Q-57-3045",
  "/_dlc_DocIdItemGuid": "aebaac92-8bbc-4d02-8778-3443c0b8d8d1",
  "/_dlc_DocIdUrl": "http://sharepoint.fda.gov/orgs/CDER-OPPQ/_layouts/DocIdRedir.aspx?ID=WMY7AAHNVM6Q-57-3045, WMY7AAHNVM6Q-57-3045"
})
>>> print(pdf.open_metadata())
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.4-c005 78.147326, 2012/08/23-13:03:03        ">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:pdf="http://ns.adobe.com/pdf/1.3/" xmlns:pdfx="http://ns.adobe.com/pdfx/1.3/" xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/" rdf:about="">
         <xmp:ModifyDate>2016-11-22T15:10:17-05:00</xmp:ModifyDate>
         <xmp:CreateDate>2016-11-18T14:55:35-05:00</xmp:CreateDate>
         <xmp:MetadataDate>2016-11-22T15:10:17-05:00</xmp:MetadataDate>
         <xmp:CreatorTool>Acrobat PDFMaker 10.1 for Word</xmp:CreatorTool>
         <xmpMM:DocumentID>uuid:1cdec4e5-e7ac-4240-87ad-b48f81b858b3</xmpMM:DocumentID>
         <xmpMM:InstanceID>uuid:005f06a1-1bcf-4890-bfc2-e94184f81e19</xmpMM:InstanceID>
         <xmpMM:subject>
            <rdf:Seq>
               <rdf:li>15</rdf:li>
            </rdf:Seq>
         </xmpMM:subject>
         <dc:format>application/pdf</dc:format>
         <dc:title>
            <rdf:Alt>
               <rdf:li xml:lang="x-default">Contract Manufacturing Arrangements for Drugs: Quality Agreements Guidance for Industry</rdf:li>
            </rdf:Alt>
         </dc:title>
         <dc:description>
            <rdf:Alt>
               <rdf:li xml:lang="x-default">Guidance for Industry</rdf:li>
            </rdf:Alt>
         </dc:description>
         <dc:creator>
            <rdf:Seq>
               <rdf:li>FDA/CDER</rdf:li>
            </rdf:Seq>
         </dc:creator>
         <dc:subject>
            <rdf:Bag>
               <rdf:li>Contract Manufacturing Arrangements for Drugs: Quality Agreements Guidance for Industry</rdf:li>
            </rdf:Bag>
         </dc:subject>
         <pdf:Producer>Adobe PDF Library 10.0</pdf:Producer>
         <pdf:Keywords>Contract Manufacturing Arrangements for Drugs: Quality Agreements Guidance for Industry</pdf:Keywords>
         <pdfx:SourceModified>D:20161118195431</pdfx:SourceModified>
         <pdfx:Company>FDA Dallas District Office</pdfx:Company>
         <pdfx:Manager>O. D. Evans</pdfx:Manager>
         <pdfx:_NewReviewCycle/>
         <pdfx:_dlc_DocId>WMY7AAHNVM6Q-57-3045</pdfx:_dlc_DocId>
         <pdfx:_dlc_DocIdItemGuid>aebaac92-8bbc-4d02-8778-3443c0b8d8d1</pdfx:_dlc_DocIdItemGuid>
         <pdfx:_dlc_DocIdUrl>http://sharepoint.fda.gov/orgs/CDER-OPPQ/_layouts/DocIdRedir.aspx?ID=WMY7AAHNVM6Q-57-3045, WMY7AAHNVM6Q-57-3045</pdfx:_dlc_DocIdUrl>
         <pdfx:Initialↂ0020Triage/>
         <pdfx:Organization/>
         <pdfx:PRODↂ0020TYPE/>
         <pdfx:OSↂ0020Response/>
         <pdfx:NCIↂ0020Category/>
         <pdfx:Orgↂ0020Type/>
         <pdfx:Dosage/>
         <pdfx:Qualityↂ0020Metric/>
         <pdfx:AssignedTo/>
         <pdfx:Resp>, </pdfx:Resp>
         <pdfx:GUIDANCEↂ0020SECTION/>
         <pdfx:ContentTypeId>0x0101006F3CD5214AFA3B4EB052EF62504A8D5C</pdfx:ContentTypeId>
         <photoshop:headline>
            <rdf:Seq>
               <rdf:li>Letterhead template</rdf:li>
            </rdf:Seq>
         </photoshop:headline>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>

>>> del pdf.Root.Metadata
>>> print(pdf.open_metadata())
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="pikepdf">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
 </rdf:RDF>
</x:xmpmeta>

>>> pdf.docinfo
pikepdf.Dictionary({
  "/AssignedTo": "",
  "/Author": "FDA/CDER",
  "/Company": "FDA Dallas District Office",
  "/ContentTypeId": "0x0101006F3CD5214AFA3B4EB052EF62504A8D5C",
  "/CreationDate": "D:20161118145535-05'00'",
  "/Creator": "Acrobat PDFMaker 10.1 for Word",
  "/Dosage": "",
  "/GUIDANCE SECTION": "",
  "/Initial Triage": "",
  "/Keywords": "Contract Manufacturing Arrangements for Drugs: Quality Agreements Guidance for Industry",
  "/Manager": "O. D. Evans",
  "/ModDate": "D:20161122151017-05'00'",
  "/NCI Category": "",
  "/OS Response": "",
  "/Org Type": "",
  "/Organization": "",
  "/PROD TYPE": "",
  "/Producer": "Adobe PDF Library 10.0",
  "/Quality Metric": "",
  "/Resp": ", ",
  "/SourceModified": "D:20161118195431",
  "/Subject": "Guidance for Industry",
  "/Title": "Contract Manufacturing Arrangements for Drugs: Quality Agreements Guidance for Industry",
  "/_NewReviewCycle": "",
  "/_dlc_DocId": "WMY7AAHNVM6Q-57-3045",
  "/_dlc_DocIdItemGuid": "aebaac92-8bbc-4d02-8778-3443c0b8d8d1",
  "/_dlc_DocIdUrl": "http://sharepoint.fda.gov/orgs/CDER-OPPQ/_layouts/DocIdRedir.aspx?ID=WMY7AAHNVM6Q-57-3045, WMY7AAHNVM6Q-57-3045"
})
>>> with pdf.open_metadata() as meta:
...     meta['dc:title'] = 'A different title'
... 
>>> print(pdf.open_metadata())
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="pikepdf">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
 <rdf:Description rdf:about=""><dc:title xmlns:dc="http://purl.org/dc/elements/1.1/"><rdf:Alt><rdf:li xml:lang="x-default">A different title</rdf:li></rdf:Alt></dc:title></rdf:Description><rdf:Description xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmp:MetadataDate="2020-04-04T23:23:43.692549" rdf:about=""/><rdf:Description xmlns:pdf="http://ns.adobe.com/pdf/1.3/" pdf:Producer="pikepdf 1.10.4" rdf:about=""/></rdf:RDF>
</x:xmpmeta>

>>> pdf.save('new.pdf')
>>> pdf.docinfo
pikepdf.Dictionary({
  "/AssignedTo": "",
  "/Company": "FDA Dallas District Office",
  "/ContentTypeId": "0x0101006F3CD5214AFA3B4EB052EF62504A8D5C",
  "/Dosage": "",
  "/GUIDANCE SECTION": "",
  "/Initial Triage": "",
  "/Manager": "O. D. Evans",
  "/NCI Category": "",
  "/OS Response": "",
  "/Org Type": "",
  "/Organization": "",
  "/PROD TYPE": "",
  "/Producer": "pikepdf 1.10.4",
  "/Quality Metric": "",
  "/Resp": ", ",
  "/SourceModified": "D:20161118195431",
  "/Title": "A different title",
  "/_NewReviewCycle": "",
  "/_dlc_DocId": "WMY7AAHNVM6Q-57-3045",
  "/_dlc_DocIdItemGuid": "aebaac92-8bbc-4d02-8778-3443c0b8d8d1",
  "/_dlc_DocIdUrl": "http://sharepoint.fda.gov/orgs/CDER-OPPQ/_layouts/DocIdRedir.aspx?ID=WMY7AAHNVM6Q-57-3045, WMY7AAHNVM6Q-57-3045"
})
```

```bash
$ exiftool new.pdf 
ExifTool Version Number         : 10.10
File Name                       : new.pdf
Directory                       : .
File Size                       : 112 kB
File Modification Date/Time     : 2020:04:04 23:24:03+08:00
File Access Date/Time           : 2020:04:04 23:24:02+08:00
File Inode Change Date/Time     : 2020:04:04 23:24:03+08:00
File Permissions                : rw-rw-r--
File Type                       : PDF
File Type Extension             : pdf
MIME Type                       : application/pdf
PDF Version                     : 1.5
Linearized                      : No
Assigned To                     : 
Company                         : FDA Dallas District Office
Content Type Id                 : 0x0101006F3CD5214AFA3B4EB052EF62504A8D5C
Dosage                          : 
GUIDANCE SECTION                : 
Initial Triage                  : 
Manager                         : O. D. Evans
NCI Category                    : 
OS Response                     : 
Org Type                        : 
Organization                    : 
PROD TYPE                       : 
Quality Metric                  : 
Resp                            : ,
Source Modified                 : D:20161118195431
Tag New Review Cycle            : 
Dlc Doc Id                      : WMY7AAHNVM6Q-57-3045
Dlc Doc Id Item Guid            : aebaac92-8bbc-4d02-8778-3443c0b8d8d1
Dlc Doc Id Url                  : http://sharepoint.fda.gov/orgs/CDER-OPPQ/_layouts/DocIdRedir.aspx?ID=WMY7AAHNVM6Q-57-3045, WMY7AAHNVM6Q-57-3045
Language                        : en-ae
Tagged PDF                      : Yes
XMP Toolkit                     : pikepdf
Title                           : A different title
Metadata Date                   : 2020:04:04 23:23:43.692549
Producer                        : pikepdf 1.10.4
Page Layout                     : OneColumn
Page Count                      : 16
```
Example pdf is get from [here](https://www.fda.gov/media/86193/download).

I also tried rewrite pdf.docinfo, and failed.
```python
>>> pdf.docinfo=pikepdf.Dictionary({})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: docinfo must be an indirect object - use Pdf.make_indirect
>>> pdf.make_indirect(pdf.docinfo)=pikepdf.Dictionary({})
  File "<stdin>", line 1
SyntaxError: can't assign to function call
>>> 
```

**Comment by jbarlow83** [comment]
Only the standard set of DocumentInfo fields will be updated when the XMP metadata is updated. This PDF you are working with defines a lot of custom of DocumentInfo fields, and there is no way of knowing how they should be converted to XMP metadata. Some XMP metadata fields should not be copied to DocumentInfo, e.g. everything in the `pdfx:` namespace.

I will update the documentation to clarify this.

You can edit pdf.docinfo directly:

```python
pdf.docinfo["Title"] = "Example"
```

To replace docinfo with an entirely new dictionary, use:
```python
pdf.docinfo = pdf.make_indirect(pikepdf.Dictionary({})
```

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by def-fun** [comment]
Ohhh, it works!

**Comment by def-fun** [comment]
@jbarlow83  
It seems that the key of docinfo should starts with `/`, for example,
```python
pdf.docinfo['/ISBN'] = '123-4-567-xxxxx-0'
pdf.docinfo['/Title'] = 'Example'
```
which can be inferred from outputs shown below:
```python
>>> import pikepdf
>>> pdf=pikepdf.open('raw.pdf')
>>> pdf.docinfo
pikepdf.Dictionary({

})
>>> print(pdf.open_metadata())
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="pikepdf">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
 </rdf:RDF>
</x:xmpmeta>

>>> with pdf.open_metadata() as meta:
...   meta['dc:title'] = 'Example'
... 
>>> pdf.docinfo
pikepdf.Dictionary({
  "/Producer": "pikepdf 1.10.4",
  "/Title": "Example"
})
```

The missing of `/` would cause  `QPDFFakeN`:
```python
>>> import pikepdf
>>> pdf=pikepdf.open('raw.pdf')
>>> pdf.docinfo
pikepdf.Dictionary({

})
>>> pdf.docinfo["Title"] = "Example"
>>> pdf.docinfo
pikepdf.Dictionary({
  "Title": "Example"
})
>>> pdf.save('out.pdf')
>>> out_pdf=pikepdf.open('out.pdf')
>>> out_pdf.docinfo
pikepdf.Dictionary({
  "/QPDFFake1": "Title",
  "/QPDFFake2": "Example"
})
```
and `QPDFFakeN` can't be found by `exiftool` or other pdf softerware:
```bash
$ exiftool out.pdf 
ExifTool Version Number         : 10.10
File Name                       : out.pdf
Directory                       : .
File Size                       : 111 kB
File Modification Date/Time     : 2020:04:05 12:23:51+08:00
File Access Date/Time           : 2020:04:05 12:23:55+08:00
File Inode Change Date/Time     : 2020:04:05 12:23:51+08:00
File Permissions                : rw-rw-r--
File Type                       : PDF
File Type Extension             : pdf
MIME Type                       : application/pdf
PDF Version                     : 1.5
Linearized                      : No
Language                        : en-ae
Tagged PDF                      : Yes
XMP Toolkit                     : pikepdf
Page Layout                     : OneColumn
Page Count                      : 16
```

**Comment by jbarlow83** [comment]
Correct, the leading slash is mandatory for all pikepdf.Name strings.
